api_platform:
  title: 'Paytop Technical Test'
  version: '1.0'
  show_webby: false
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  defaults:
    pagination_items_per_page: 10
    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
